name: nss_jmieti
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  logger: ^1.3.0
  flutter_native_splash: ^2.2.18
  flutter:
    sdk: flutter
  http: ^0.13.5
  webview_flutter: ^3.0.0
  get: ^4.6.5
  #flutter_webview_plugin: ^0.4.0
  image_picker: ^0.8.7
  video_player: ^2.6.0
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/front_screen/
    - assets/
  
